name: church_connect
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.3
  path_provider: ^2.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  carousel_slider: ^5.0.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3
  path: ^1.9.0
  flutter_markdown: ^0.6.20
  pdf: ^3.10.8
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  audio_session: ^0.1.18
  rxdart: ^0.27.7
  intl: ^0.18.1
  share_plus: ^7.2.1
  fluttertoast: ^8.2.4
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/kjv.json
    - assets/images/sermon_header.jpg
