name: church_connect
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.2
  path: ^1.9.0
  intl: ^0.18.1
  flutter_markdown: ^0.6.20
  pdf: ^3.10.8
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/kjv.json
